### ISSUE TITLE
Kesalahan untuk akun

### ISSUE THREAD

**Issue by ebelizm** [wrightL-dev/FUNCTOR-NODE#1]
Request failed with status code 400

**Comment by wrightL-dev** [comment]
Send a screenshot of the error

**Comment by ebelizm** [comment]
> Send a screenshot of the error

![image](https://github.com/user-attachments/assets/762eee09-8410-4476-8b70-b4763fed8006)

**Comment by wrightL-dev** [comment]
![IMG_20241115_133649](https://github.com/user-attachments/assets/2e6958d7-3508-46d1-9c10-034374b66b9c)

This error occurs because the email or password does not match, as shown in this image. I entered a random email and password, and the response was a 400 error Or Email and password match the account.txt format or don't use the | delimiter Example: user1@gmail.com|12345678

**Comment by wrightL-dev** [comment]
![IMG_20241115_133649](https://github.com/user-attachments/assets/7141b8e2-22e3-4f09-9f43-c93e5497c56a)


This error occurs because the email or password does not match, as shown in this image. I entered a random email and password, and the response was error 400. Or Email and password do not match the akun.txt format or do not use | delimiter Example: user1@gmail.com|12345678

**Comment by ebelizm** [comment]
aneh sih. udah reset password juga tetep ga bisa login di web nya
"OTP not found in the database"

**Comment by wrightL-dev** [comment]
> aneh sih. udah reset password juga tetep ga bisa login di web nya "OTP not found in the database"

Cek spam email biasanya masuk di situ, kalo gak daftar ulang aja
